# app.py
import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from src.preprocessor import preprocess_code
from src.detectors import PlagiarismDetector
from src.semantic import SemanticAnalyzer
from src.ai_detector import AIDetector

# streamlit run C:\Users\ad\Downloads\codepython\project\fraud_detection_system\app.py
st.set_page_config(layout="wide", page_title="Python Fraud Detection System")


@st.cache_resource
def load_models():
    semantic_analyzer = SemanticAnalyzer(lazy_load=True)
    ai_detector = AIDetector(use_perplexity=False)  # fast default; enable if GPU available
    return semantic_analyzer, ai_detector


st.title("Python Fraud Detection System")
st.markdown("### Plagiarism & AI-Generated Code Detection")

st.sidebar.header("Configuration")
k_gram = st.sidebar.slider("K-Gram Length", 3, 10, 5)
window_size = st.sidebar.slider("Window Size", 3, 10, 4)
similarity_threshold = st.sidebar.slider("Similarity Threshold", 0.0, 1.0, 0.5)

st.sidebar.markdown("---")
st.sidebar.subheader("AI Detection Settings")
ai_threshold = st.sidebar.slider(
    "AI Detection Threshold",
    min_value=0.0,
    max_value=1.0,
    value=0.60,
    step=0.05,
    help="Files with p_ai ≥ threshold are flagged. Higher = fewer false positives.",
)

uploaded_files = st.sidebar.file_uploader(
    "Upload Python Files", type=["py"], accept_multiple_files=True
)

if uploaded_files:
    st.info(f"Processing {len(uploaded_files)} files...")

    file_contents = {}
    file_names = []

    for uploaded_file in uploaded_files:
        content = uploaded_file.read().decode("utf-8")
        file_contents[uploaded_file.name] = content
        file_names.append(uploaded_file.name)

    semantic_analyzer, ai_detector = load_models()
    plagiarism_detector = PlagiarismDetector(k_gram_len=k_gram, window_size=window_size)

    tab_ai, tab_sim = st.tabs([
        "AI Code Detection (Stylometry)",
        "Pairwise Similarity Analysis",
    ])

    with tab_ai:
        st.subheader("AI Code Detection (Stylometry)")
        st.caption(
            "Analyses whitespace, comments, naming, and style patterns to estimate "
            "the probability that code was generated by an AI assistant."
        )

        ai_results = []
        progress_bar = st.progress(0)

        for i, name in enumerate(file_names):
            raw_code = file_contents[name]  # RAW code — never preprocessed
            result = ai_detector.analyze(raw_code, threshold=ai_threshold)

            ai_results.append({
                "File": name,
                "AI Score": result["score"],
                "p_ai": f'{result["p_ai"]:.3f}',
                "Flag": "🔴 YES" if result["flag"] else "✅ NO",
                "Top Signals": " · ".join(result["signals"][:3]),
                "_result": result,  # keep for expander
                "_code": raw_code,
            })
            progress_bar.progress((i + 1) / len(file_names))

        df_ai = pd.DataFrame(ai_results)
        display_cols = ["File", "AI Score", "p_ai", "Flag", "Top Signals"]

        def _highlight_flag(row):
            if "YES" in str(row["Flag"]):
                return ["background-color: #ffcccc"] * len(row)
            return [""] * len(row)

        st.dataframe(
            df_ai[display_cols].style.apply(_highlight_flag, axis=1),
            width='stretch',
            hide_index=True,
        )

        flagged_count = sum(1 for r in ai_results if "YES" in r["Flag"])
        if flagged_count:
            st.warning(f"⚠️ {flagged_count}/{len(file_names)} file(s) flagged as likely AI-generated (threshold ≥ {ai_threshold:.2f})")
        else:
            st.success(f"No files flagged at threshold {ai_threshold:.2f}")

        st.markdown("---")
        st.markdown("#### File Details")
        selected_file = st.selectbox("Select file to inspect", file_names, key="ai_file_select")

        if selected_file:
            entry = next(r for r in ai_results if r["File"] == selected_file)
            res = entry["_result"]

            col_score, col_pai, col_flag = st.columns(3)
            col_score.metric("AI Score", f'{res["score"]}/100')
            col_pai.metric("p(AI)", f'{res["p_ai"]:.3f}')
            col_flag.metric("Flagged", "🔴 YES" if res["flag"] else "✅ NO")

            st.markdown("**Signals:**")
            for sig in res["signals"]:
                st.markdown(f"- {sig}")

            with st.expander("Source Code", expanded=False):
                st.code(entry["_code"], language="python")

            with st.expander("Feature Snapshot", expanded=False):
                details = {k: v for k, v in res["details"].items() if k != "signal_breakdown"}
                feature_df = pd.DataFrame(
                    [{"Feature": k, "Value": f"{v}" if isinstance(v, bool)
                      else f"{v:.4f}" if isinstance(v, float)
                      else str(v)}
                     for k, v in sorted(details.items())],
                )
                st.dataframe(feature_df, width='stretch', hide_index=True)

            with st.expander("Signal Breakdown", expanded=False):
                breakdown = res["details"].get("signal_breakdown", {})
                if breakdown:
                    sig_df = pd.DataFrame(
                        [{"Signal": k, "Strength": f"{v:.1%}"} for k, v in
                         sorted(breakdown.items(), key=lambda x: x[1], reverse=True)]
                    )
                    st.dataframe(sig_df, width='stretch', hide_index=True)

    with tab_sim:
        st.subheader("Pairwise Similarity Analysis")

        if len(file_names) > 1:
            similarity_data = []

            matrix_size = len(file_names)
            plagiarism_matrix = pd.DataFrame(0.0, index=file_names, columns=file_names)
            semantic_matrix = pd.DataFrame(
                index=file_names, columns=file_names, dtype=float
            ).fillna(0.0)

            pairs_to_check = []
            for i in range(matrix_size):
                for j in range(i + 1, matrix_size):
                    pairs_to_check.append((file_names[i], file_names[j]))

            pair_progress = st.progress(0)
            high_risk_pairs = []

            code_preprocessed = {
                name: preprocess_code(content) for name, content in file_contents.items()
            }

            for idx, (name1, name2) in enumerate(pairs_to_check):
                score_plag = plagiarism_detector.calculate_similarity(
                    code_preprocessed[name1], code_preprocessed[name2]
                )
                score_sem = semantic_analyzer.calculate_similarity(
                    file_contents[name1], file_contents[name2]
                )

                plagiarism_matrix.loc[name1, name2] = score_plag
                plagiarism_matrix.loc[name2, name1] = score_plag

                semantic_matrix.loc[name1, name2] = score_sem
                semantic_matrix.loc[name2, name1] = score_sem

                risk_level = "Low"
                if score_plag > similarity_threshold or score_sem > similarity_threshold:
                    risk_level = (
                        "High"
                        if (score_plag > 0.7 or score_sem > 0.8)
                        else "Moderate"
                    )
                    high_risk_pairs.append({
                        "File A": name1,
                        "File B": name2,
                        "MOSS Similarity": f"{score_plag:.2f}",
                        "Semantic Similarity": f"{score_sem:.2f}",
                        "Risk Level": risk_level,
                    })

                pair_progress.progress((idx + 1) / len(pairs_to_check))

            col1, col2 = st.columns(2)
            with col1:
                st.write("#### MOSS Similarity Heatmap")
                fig1, ax1 = plt.subplots()
                sns.heatmap(
                    plagiarism_matrix.astype(float), annot=True, cmap="Reds", ax=ax1
                )
                st.pyplot(fig1)

            with col2:
                st.write("#### Semantic Similarity Heatmap")
                fig2, ax2 = plt.subplots()
                sns.heatmap(
                    semantic_matrix.astype(float), annot=True, cmap="Blues", ax=ax2
                )
                st.pyplot(fig2)

            if high_risk_pairs:
                st.warning(f"Found {len(high_risk_pairs)} suspicious pairs!")
                st.table(pd.DataFrame(high_risk_pairs))

                st.subheader("Code Comparison Viewer")
                selected_pair = st.selectbox(
                    "Select Pair to Compare",
                    [f"{p['File A']} vs {p['File B']}" for p in high_risk_pairs],
                )

                if selected_pair:
                    f1, f2 = selected_pair.split(" vs ")
                    c1, c2 = st.columns(2)
                    with c1:
                        st.write(f"**{f1}**")
                        st.code(file_contents[f1], language="python")
                    with c2:
                        st.write(f"**{f2}**")
                        st.code(file_contents[f2], language="python")
        else:
            st.info("Upload at least 2 files for similarity analysis.")

else:
    st.write("Upload Python files from the sidebar to start analysis.")
